### ISSUE TITLE
Backend: Profiles

### ISSUE THREAD

**Issue by RoyalOrangefire** [gophermatch/gophermatch#6]
Profile information includes:
- Bio (text chunk)
- Preferences (For displaying to others. See #8)
- Q&A (text chunk)
- Pictures (up to 5 per user)

Q&A: Could change often, so store it as json (?)
Pictures: we could give each picture a unique ID, store it as a file (not in db). Then we store the IDs as a JSON array in the Profile DB table.

Tasks:
- [ ] Initialize profile information (Upon [account creation](#2) or?) (SQL)
- [ ] Retrieving profile information (SQL)
- [ ] Retrieving list of questions for Q&As (SQL)
- [ ] Updating your own profile information (SQL)
- [ ] API Routes: Retrieving profile information (GET)
- [ ] API Routes: Updating profile information (PUT), need to verify that they are updating themselves (See #1).
- [ ] Generate IDs for storing pictures in the server's folder (Might not be necessary depending on storage)

**Comment by zachkaupp** [comment]
@AlienIdeology ping me when you commit the /database profile.js and then i'll write the /routes profile.js

**Comment by AlienIdeology** [comment]
@zachkaupp done
